envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
name: profile-demo
region: nyc
services:
- environment_slug: python
  envs:
  - key: DISABLE_COLLECTSTATIC
    scope: RUN_AND_BUILD_TIME
    value: "1"
  github:
    branch: main
    deploy_on_push: true
    repo: connorswanson1/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: pythonwebapps-02-profile-app
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: 03/Superhero
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: connorswanson1/PythonWebApps
  name: pythonwebapps-02-profile-app-sta
  routes:
  - path: /static
  source_dir: 03/Superhero/static
